### ISSUE TITLE
Tag docker images

### ISSUE THREAD

**Issue by thunderstorm99** [limbas/limbas-docker#2]
As a recommendation: It would be nice if you could tag your images with some sort of version number. That way you have a history on hub.docker.com, leaving your customers the possibility to pin down their deployment to one specific version. With only one tag (latest) you won't necessarily have the same version, depending on the date of download.

**Comment by limbas** [comment]
Thanks for your comment. Better late than never: From version 5 onwards, all images will be updated accordingly with version number and other information such as PHP version or web server used.
