### ISSUE TITLE
No connection to DB

### ISSUE THREAD

**Issue by mucnet** [limbas/limbas-docker#3]
I'm unable to fire up limbas with the provided environment and it looks like there is a problem with connection to the DB:
![image](https://user-images.githubusercontent.com/33168225/155761123-f0f093c3-cc77-439a-bb90-617518cbcc33.png)

`db_1   | 2022-02-25 17:04:36.181 UTC [1] LOG:  starting PostgreSQL 14.2 (Debian 14.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

db_1   | 2022-02-25 17:04:36.181 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1   | 2022-02-25 17:04:36.181 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1   | 2022-02-25 17:04:36.186 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1   | 2022-02-25 17:04:36.190 UTC [65] LOG:  database system was shut down at 2022-02-25 17:04:36 UTC
db_1   | 2022-02-25 17:04:36.215 UTC [1] LOG:  database system is ready to accept connections
db_1   | 2022-02-25 17:26:10.631 UTC [145] FATAL:  role "postgres" does not exist
db_1   | 2022-02-25 17:30:30.416 UTC [189] FATAL:  role "postgres" does not exist
db_1   | 2022-02-25 17:33:10.626 UTC [197] FATAL:  role "postgres" does not exist`

**Comment by mucnet** [comment]
I think i might found a fix for this issue, as limiting the DB container to postgreSQL version 10 instead of no tag (meaning using latest version) does work:
https://github.com/limbas/limbas-docker/blob/master/db/dockerfile

`FROM postgres `   
_changed_to_
`FROM postgres:10`

**Comment by jaennert** [comment]
Habe Limbas unter Docker installiert und habe auch das hier geschilderte Problem. Leider habe ich nicht genug Erfahrung mit Docker, um die diese Änderung durchzuführen. Unter Limbas und im Docker Hub finde ich keine aktuellen Versionen.

**Comment by mucnet** [comment]
Wie beschrieben besteht eine Lösung darin, im Dockerfile die Version der Postgres Datenbank auf Version 10 festzusetzen. 

Alternativ einfach diese Fork verwenden:

https://github.com/mucnet/limbas-docker/

**Comment by jaennert** [comment]
Mit dem Fork funktioniert es. Erhalte allerdings die Meldung:

Database Vendor:	postgres - 100021 - UTF8 
Version Conflict! $DBA['VERSION'] in include_db.lib has to be updated!

Aber ein großer Schritt vorwärts. Danke
